import React from 'react';
import Head from 'next/head';
import Header from './Header';
import Footer from './Footer';
import { useRouter } from 'next/router';

const Layout = ({children}) => {
    const router = useRouter();
    let currentRoute;
    if(router.asPath === "/"){
        currentRoute = "Home";
    } else {
        if(!router.asPath[1]) currentRoute = null;
        currentRoute = router.asPath.slice(1).replace(router.asPath[1], router.asPath[1].toUpperCase());
    }
    return (  
        <>
            <Head>
                <title>GuitarLA Next App - {currentRoute}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header/>
            {children}
            <Footer/>  
        </>
     );
}
 
export default Layout;